name: prod test & deploy workflow
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgres db: 'nc_news_test'
          postgres user: 'test_user'
          postgres password: 'password'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: PGDATABASE=nc_news_test PGUSER=test_user PGPASSWORD=password npm t

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to prod
        uses: johnbeyon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}